### ISSUE TITLE
Fields are resetting upon loading a mod

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceymodgeons#1]
[morefluff.zip](https://github.com/TerryCavanagh/diceymodgeons/files/3321306/morefluff.zip)

Whenever I edit this mod with the editor and save it, a lot of fields get changed/removed:

![image](https://user-images.githubusercontent.com/32357485/60027876-392caa00-9696-11e9-8da5-70b0fff93d87.png)
"Needs Total" is set to Null for all items which had a value in that field

![image](https://user-images.githubusercontent.com/32357485/60027913-4ea1d400-9696-11e9-99bc-d2364b3fd7d3.png)
"Witch Spell" is also set to Null

![image](https://user-images.githubusercontent.com/32357485/60027943-5f524a00-9696-11e9-9c8e-9df617488736.png)
The headers are reset to the 0.17 versions of them, and any data in these columns are erased.

If you open the file in any other csv editor before using it in the tool, you can see that the "Needs Total" and "Witch Spell" fields have numbers in them, and the headers are up to date.

**Comment by mrcdk** [comment]
Looks like your merge files have some issues and they break everything else 😓 For example, the equipment.csv in the _merge folder doesn't have the new headers and they are overriden everywhere else (the editor expects that all the files are in the same mod API version)

The other problem is that in `fighters.csv` in the `_merge` folder, the headers and values are wrong in some of them like these ones:
![https://i.imgur.com/2VoBVvC.png](https://i.imgur.com/2VoBVvC.png)

The editor doesn't know how to deal with those and save them wrong.

The `Null` issue has been fixed.

**Comment by JuniorUdale** [comment]
Ah, that's fixed things! The tool works fine now, thanks for the help.
