### ISSUE TITLE
Will not let me save

### ISSUE THREAD

**Issue by TheLemon27** [TerryCavanagh/diceymodgeons#13]
I am trying to make a mod (a simple one, just adding a few equipment and status effects) when i try to save, my equipment still has the asterisk next to it, signifying it has not been saved and when i try to exit the program, it says "save changes before exiting?" I have already lost progress due to this  even though i clicked "save" as i quit.

pls help me

**Comment by TheLemon27** [comment]
here is what the command prompt-like window says when i try to create something and save it:

File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/fighters.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/fighters.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/equipment.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/equipment.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/items.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/items.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/statuseffects.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/characters.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/characters.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/episodes.csv doesn't exist
File C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/episodes.csv doesn't exist
CREATE 2: New Equipment (Null) = Null
SCRIPT ERROR: CSVData.create: Invalid get index 'Script: On any countdown reduce' (on base: 'Dictionary').
          At: res://Database.gd:468
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/fighters.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/fighters.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/equipment.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/equipment.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/items.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/items.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/statuseffects.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/characters.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/characters.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_append/data/text/episodes.csv
No content for C:/Program Files (x86)/Steam/steamapps/common/Dicey Dungeons/mods/[Mod]/_merge/data/text/episodes.csv

hope someone can help!

**Comment by mrcdk** [comment]
Hey, sorry! The software was in a pre-alpha state at that point. It should be better now! Closing this issue.

If you or anyone else have a similar issue with the newer versions, please open a new issue! Thanks!
