### ISSUE TITLE
Upgraded, Downgraded, etc. versions of equipment should inherit the properties and scripts of the normal version when created, rather than being created from scratch

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceymodgeons#16]
And possibly Weakened should inherit from Downgraded if that already exists, and Deck Upgrade should inherit from Upgraded

**Comment by mrcdk** [comment]
Done in https://github.com/TerryCavanagh/diceymodgeons/commit/d9932e8e798a80541c84b8b59609aefd5dc44538, thanks!
