### ISSUE TITLE
Equipment with 3 lines of description doesn't display right

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceymodgeons#19]
![image](https://user-images.githubusercontent.com/11216597/71040273-3fa35800-20f4-11ea-8916-38b3f7302d94.png)
Equipment with 3 lines almost always works in vanilla dicey, only fails when the equipment is size 1 *and* the slot has text below it, e.g. "needs 1", "needs doubles", or "must equal x"

**Comment by mrcdk** [comment]
We are using Godot's [RichTextLabel](https://docs.godotengine.org/en/stable/classes/class_richtextlabel.html) node to render the text. I've tweaked it a bit so it's closer to what's shown in the game. It's not perfect though. The only real fix would be to port the game code to Godot but that's a task I don't plan to do in the near future.
