### ISSUE TITLE
Blue, cyan, and brightcyan all show as the same color

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceymodgeons#2]
![](https://i.frogbox.es/lsm)
As do gray and white

**Comment by ncrecc** [comment]
Is this an issue with modgeons or dd itself?

**Comment by ShinyKitten07** [comment]
dd, older versions used to have them as all being separate, but after the art was redone they were merged.
![equipcolors](https://user-images.githubusercontent.com/19874772/60042589-eee60180-9672-11e9-8b50-37be57841e86.png)

**Comment by ncrecc** [comment]
Moved to https://github.com/TerryCavanagh/diceydungeonsbeta/issues/235
