### ISSUE TITLE
Comments aren't recognized

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceymodgeons#20]
![image](https://user-images.githubusercontent.com/11216597/71040928-c86ec380-20f5-11ea-8807-a32fad50111b.png)

**Comment by mrcdk** [comment]
We are using Godot's [TextEdit](https://docs.godotengine.org/en/stable/classes/class_textedit.html) node which doesn't expose enough functionality for this. I exposed it at some point in a custom build but I don't feel like maintaining it in sync with master. I made a [pull request](https://github.com/godotengine/godot/pull/29823) to add it to godot but the consensus was to [split the node into two](https://github.com/godotengine/godot/issues/31739). We need to wait for Godot 3.2.x or 4.0 to add this.

**Comment by mrcdk** [comment]
Actually, nvm. No need to wait for the rewrite! I was looking at the documentation again and found out this [`TextEdit.add_color_region()`](https://docs.godotengine.org/en/stable/classes/class_textedit.html#class-textedit-method-add-color-region) which is what we want to support comments!

Thanks! Fixed!
