### ISSUE TITLE
Remove automatic line breaks in card preview

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceymodgeons#21]
![image](https://user-images.githubusercontent.com/11216597/71041137-50ed6400-20f6-11ea-9a18-85a2af76735e.png)
Even if the text actually does fit on 1 line in-game (or slightly clips the card border), modgeons assumes it has to go down one row

**Comment by mrcdk** [comment]
We are using Godot's [RichTextLabel](https://docs.godotengine.org/en/stable/classes/class_richtextlabel.html) node to render the text. I've tweaked it a bit so it's closer to what's shown in the game. It's not perfect though. The only real fix would be to port the game code to Godot but that's a task I don't plan to do in the near future.
