### ISSUE TITLE
There should be a "Cast Backwards?" option for equipment

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceymodgeons#31]
![unknown](https://user-images.githubusercontent.com/32357485/73946122-52b0f800-48ed-11ea-9f66-31f7ed2cca12.png)

Might be a simple oversight, but there's no override for the "cast backwards?" field for equipment, it seems.

**Comment by mrcdk** [comment]
It's not an oversight, we've been planning to change that field for some time but we always forget to do it 😅

**Comment by basmith7** [comment]
I think that's the definition of an oversight.

**Comment by JuniorUdale** [comment]
Fixed in the current version.
