### ISSUE TITLE
Setting two slots to "Must equal X" and then removing one slot still makes it appear as "Must equal X" in game

### ISSUE THREAD

**Issue by HallowedFlux** [TerryCavanagh/diceymodgeons#33]
The value is probably not properly ignored if the amount of slots is back to one. this would make it so that you can have a "Must equal 8" while having only one die slot as shown below, which makes it unable to be played.
![afbeelding](https://user-images.githubusercontent.com/29779604/74517919-51965100-4f13-11ea-86c7-07623fa789d2.png)
![afbeelding](https://user-images.githubusercontent.com/29779604/74518087-8b675780-4f13-11ea-8a63-d75511b9f645.png)

**Comment by mrcdk** [comment]
This is fixed! Thanks!
