### ISSUE TITLE
|| should become # instead of ,, when saved

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceymodgeons#34]
Rusty Sword has the code `if((self.hp / self.maxhp < 0.25) # self.hp <= 6)`. However, this gets changed to `if((self.hp / self.maxhp < 0.25) || self.hp <= 6) ` in Modgeons, which gets saved as `if((self.hp / self.maxhp < 0.25) ,, self.hp <= 6) ` because `|` automatically turns into `,`

Consider adding a special case that `||` should become `#` when saved, since that's how we need to type boolean or.

**Comment by mrcdk** [comment]
This should be fixed!  thanks!
