### ISSUE TITLE
Commas in equipment names are not converted to bracketed semicolons

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceymodgeons#35]
![image](https://user-images.githubusercontent.com/11216597/84601032-7b24a200-ae4b-11ea-871f-639ee090ec5c.png)
(see "What Even,,,,,")
This doesn't really work right because of TerryCavanagh/diceydungeons.com/issues/1475 but that's totally separate

**Comment by mrcdk** [comment]
This is now working! Thanks!
