### ISSUE TITLE
Changing an equipment's category to Backup/Skillcard does not remove slots

### ISSUE THREAD

**Issue by redpepper74** [TerryCavanagh/diceymodgeons#36]
![broken-backup](https://user-images.githubusercontent.com/63315960/85884213-e190b500-b7a7-11ea-8af1-edc7cc1029b2.gif)
When an equipment is changed from Item/Weapon/Magic/Shield to Backup/Skillcard, the slots UI is hidden, but any slots that were previously on the item remain. The UI hiding lead me to think that it just set the number of slots to 0, however this wasn't the case. 

I suggest either setting the amount of slots to 0 when you change it, or leave the slots UI and show a warning if the number isn't zero.

**Comment by mrcdk** [comment]
Fixed! Thanks!
