### ISSUE TITLE
Outdated upgrade modifiers that only affect the upgrade description should be hidden from the "upgrade modifier" dropdown

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceymodgeons#38]
Upgrade descriptions (e.g. "upgrading X makes it more powerful") are no longer used for anyone but Jester, and only because Jester's upgrade screen hasn't yet received a redesign to account for Ned (TerryCavanagh/diceydungeonsbeta/issues/309). There remain some upgrade modifiers that are identical to change_power but have a different upgrade description:

- change_poison
- change_requirements
- change_description
- change_boomerang
- change_countdown
- change_backfire
- change_towershield

Since this disambiguation isn't necessary at all, this confuses newbies at best, and these options shouldn't be selectable.

**Comment by mrcdk** [comment]
Fixed! Thanks!
