### ISSUE TITLE
Modgeons ignores write-locked files

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceymodgeons#39]
Should probably display things from write-locked files but note they're locked, e.g. if _append\equipment.csv is write-locked the appended equipment should be accessible in the equipment editor but should have a lock symbol or something and "write-locked" written somewhere. Maybe allow the user to draft changes to write-locked files but throw an error if they try to save while something's locked

**Comment by mrcdk** [comment]
This won't be possible. Godot doesn't have any way to check if the file is locked or not. The only thing I can use to test it (at least on windows, I've not tested on other platforms) is that the [`File.file_exists()`](https://docs.godotengine.org/en/stable/classes/class_file.html#class-file-method-file-exists) function will return `false` if the file is locked but will also return `false` if the file doesn't exist so it's not useful for mod related files. I'm using it in some places to detect locked game files though.
