### ISSUE TITLE
When trying to set countdown variable to 0, Modgeons force-sets it to 1

### ISSUE THREAD

**Issue by plasmaster09** [TerryCavanagh/diceymodgeons#41]
Self-explanatory. When trying to set the countdown to 0 (for example, if you changed the slot type to CD but changed your mind and want it to not be a countdown item), Modgeons instead sets it to 1 when you try to do so. Only way to fix this is to open it up in a spreadsheet editor and set it there.

**Comment by mrcdk** [comment]
Fixed! Thanks!
