### ISSUE TITLE
Custom symbols aren't showing up

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceymodgeons#44]
![image](https://user-images.githubusercontent.com/32357485/93450490-f3c54f80-f8cd-11ea-82ab-14efe0e82b26.png)

[examplesymbol.zip](https://github.com/TerryCavanagh/diceymodgeons/files/5237830/examplesymbol.zip)

**Comment by mrcdk** [comment]
Fixed in https://github.com/TerryCavanagh/diceymodgeons/commit/990ad5f0303cff6cfa246607a8aa16802dddcc0f! Thanks!
