### ISSUE TITLE
No convenient option for flexible generators, which makes changing the generators (without backup files from 1.8) a pain

### ISSUE THREAD

**Issue by WhoNeedsAUsrName** [TerryCavanagh/diceymodgeons#48]

**Comment by ncrecc** [comment]
"No convenient option"?

**Comment by WhoNeedsAUsrName** [comment]
While flexible generators are technically possible to add in a modgeons, you would need to manually create the script files, and that's assuming that it's possible in the first place

**Comment by mrcdk** [comment]
Could you elaborate a bit more? You can create custom txt files, hx scripts or csv files in the `Custom Scripts` tab so you can create the files there.

**Comment by WhoNeedsAUsrName** [comment]
While you technically could, there are two problems I see, A)you would need to manually create each item pool script, rather than copy/pasting and editing the vanilla files. And B) The `Create Custom Script` overwrites any file names the same thing, with no option (that I could see) to open an existing script.

**Comment by mrcdk** [comment]
I've added a "copy from game" button in the custom scripts tab so you can copy a file from the game folder to the mod folder and edit it without any worries. 

I think this fixes this issue so I'll close it! Thanks!

![y8QP0IrsNT](https://user-images.githubusercontent.com/483531/93910956-160e0180-fd02-11ea-8b11-1f58d0a118db.gif)

**Comment by WhoNeedsAUsrName** [comment]
Cool
