### ISSUE TITLE
Can only pick Monstermode skillcard for episodes

### ISSUE THREAD

**Issue by Robjection** [TerryCavanagh/diceymodgeons#49]
When I try to change the skillcard for an episode, the only one it lists as an option is Monstermode.

![image](https://user-images.githubusercontent.com/71552920/93666543-016a0900-fa77-11ea-8217-dda7742eeee5.png)

**Comment by mrcdk** [comment]
Fixed in https://github.com/TerryCavanagh/diceymodgeons/commit/508bae44a1e0a35562d1cde7463b3c1d3c680ad3! thanks!
