### ISSUE TITLE
Modgeons is adding tabs for indentation, which is causing errors

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceymodgeons#7]
![image](https://user-images.githubusercontent.com/32357485/60114433-b9710f00-976b-11e9-9b76-24f3f9e1f684.png)
![image](https://user-images.githubusercontent.com/32357485/60114479-d0176600-976b-11e9-9480-ee6e7cf8404b.png)

This script crashes the game on execute - by default, any loops will be indented like this.

![image](https://user-images.githubusercontent.com/32357485/60114518-e02f4580-976b-11e9-8595-7ee4b648d05e.png)
![image](https://user-images.githubusercontent.com/32357485/60114526-e3c2cc80-976b-11e9-8711-999e45dcc888.png)

This script doesn't crash the game on execute - it's the exact same as the previous script, but with the tab indentations removed.

**Comment by mrcdk** [comment]
Fixed, thanks!
