### ISSUE TITLE
Don't sort enemy equipment alphabetically

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceymodgeons#9]
The author-specified order is often important.

**Comment by ncrecc** [comment]
Or add a checkbox to switch between alphabetical sort and author-intended sort? Alphabetical sort usually makes it easier to find items, and it's what the in-game editor uses.

**Comment by onetruepurple** [comment]
In the enemy equipment list.

**Comment by mrcdk** [comment]
Fixed.
